### ISSUE TITLE
How to quote variable name?

### ISSUE THREAD

**Issue by xuchunyang** [Malabarba/names#21]
For example, I want to use `foo-` namespace for the code:

```elisp
(defvar foo-history nil)
(read-string "> " nil 'foo-history)
```
I've tried
```elisp
(define-namespace foo-

(defvar history nil)
(read-string "> " nil 'history)

)
```
`'history` can not expand to `'foo-history`, I know it is expected, but how to make it expanded?

**Comment by Malabarba** [comment]
Yes, it is expected. It is impossible for Names to know for sure when 'history refers to a variable name and when it is just a symbol provided for some other purpose, so it errs on the side of caution.
The correct thing to do here is simply to write the full name `'foo-history`.

Alternatively, you can tell Names to expand the short names by adding the `:assume-var-quote` keyword to your namespace declaration. So it would look like:

    (define-namespace foo- :assume-var-quote
    ;; Rest of code ...
    )

**Comment by xuchunyang** [comment]
Well, use the full name now, thanks for your help.
