### ISSUE TITLE
Cannot apply namespace in cl-destructuring-bind (x . y)

### ISSUE THREAD

**Issue by kosh04** [Malabarba/names#26]
```elisp
(require 'cl-lib)

(define-namespace foo-
(defun make-pair (x y)
  (cons x y))
(cl-destructuring-bind (x . y)
    ;; expect (foo-make-pair 1 2), but cannot apply `foo-' namespace
    (make-pair 1 2)
  (format "x=%s, y=%s" x y))
)
;;-> error: (void-function make-pair)
```

Is this behavior would be a known problem?

**Comment by Malabarba** [comment]
Unfortunately, it's a bug in the edebug spec of cl-destructuring-bind.
In fact, it even affects edebug itself. Just try to hit `C-u C-M-x` on the following snippet:

    (cl-destructuring-bind (x . y)
        '(1 . 2)
      x)

You could go even simpler. `C-u C-M-x` on the following snippet also doesn't work:

    (cl-destructuring-bind x
        2
      x)

The only think we can do is report these with `M-x report-emacs-bug`.

**Comment by kosh04** [comment]
Thanks for your quick reply.

I'll try to bug report about edebug, as soon as solution is found.
