### ISSUE TITLE
are you sure aggressive-indent uses names?

### ISSUE THREAD

**Issue by tpapp** [Malabarba/names#27]
I does not look like it.

An example of a library that uses names would be nice.

**Comment by tpapp** [comment]
I found [camcorder](https://github.com/Malabarba/camcorder.el), which is a fairly complete example, maybe you could mention that instead in the README.

**Comment by Malabarba** [comment]
Yes, sorry. That information on the readme is a bit old. Aggressive-indent no longer uses Names. Instead, you can see camcorder for an example. That said, nowadays I don't use Names for new stuff anymore. I generally prefer [Nameless](https://github.com/Malabarba/nameless).

**Comment by tpapp** [comment]
Thanks. `Nameless` is indeed very nice, and I think I will use that. Perhaps you could add a remark to the `README` of `names` about how you are no longer actively using it and users should consider `Nameless`.

**Comment by Malabarba** [comment]
True! Done.
